main/urls.py
from django.conf.urls import url
from . import views

app_name = "main"

urlpatterns = [
    url(r'^$', views.paper_presentation, name='paper_presentation'),
    url(r'^about/$', views.about, name='about'),
    url(r'^accounts/register/$', views.register, name='register'),
    url(r'^accounts/login/$', views.user_login, name='user_login'),
    url(r'^accounts/logout/$', views.user_logout, name='user_logout'),
    url(r'^accounts/password-reset/$',
        views.user_trouble_logging_in, name='user_trouble_logging_in'),
    url(r'^accounts/password-change/$',
        views.user_password_change, name='user_password_change'),
    url(r'^pepadmin/upload-to-drive/(?P<pk>\d+)/$',
        views.upload_to_drive, name='upload_to_drive'),
    url(r'^pepadmin/check-duplicate-abstracts/$',
        views.check_duplicate_abstracts, name='check_duplicate_abstracts'),
    url(r'^pepadmin/$', views.pepadmin, name='pepadmin'),
    url(r'^portal/$', views.portal, name='portal'),
    url(r'^portal/abstract-submission/$',
        views.abstract_submission, name='abstract_submission'),
    url(r'^portal/abstract-review/(?P<pk>\d+)/$',
        views.abstract_review, name='abstract_review'),
    url(r'^portal/assign-professor/(?P<pk>\d+)/$',
        views.assign_professor, name='assign_professor'),
    url(r'^portal/paper-submission/$',
        views.paper_submission, name='paper_submission'),
    url(r'^portal/paper-review/(?P<pk>\d+)/$',
        views.paper_review, name='paper_review'),
    url(r'^portal/paper-abstract-submission/$',
        views.paper_abstract_submission, name='paper_abstract_submission'),
]

pep/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth import views
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import ProfessorProfile, ParticipantProfile, Abstract, Paper


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class ParticipantProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ParticipantProfileForm, self).__init__(*args, **kwargs)
        self.fields['college'].required = True

    class Meta:
        model = ParticipantProfile
        fields = ('author', 'coauthor', 'phone1', 'phone2', 'college')


class AssignProfessorForm(forms.ModelForm):
    class Meta:
        model = Abstract
        fields = ('professor',)


class AbstractForm(forms.ModelForm):
    class Meta:
        model = Abstract
        fields = ('title', 'document', 'category')


class PaperForm(forms.ModelForm):

    class Meta:
        model = Paper
        fields = ('abstract','document',)

class PaperAbstractNewForm(forms.ModelForm):

    class Meta:
        model = Paper
        fields = ('document',)

class AbstractReUploadForm(forms.ModelForm):
    class Meta:
        model = Abstract
        fields = ('document',)

class AbstractReviewForm(forms.ModelForm):
    class Meta:
        model = Abstract
        fields = ('review',)
        widgets = {
            'review': forms.Textarea(attrs={'cols': 80, 'rows': 3}),
        }

class PaperReviewForm(forms.ModelForm):
    class Meta:
        model = Paper
        fields = ('review',)
        widgets = {
            'review': forms.Textarea(attrs={'cols': 80, 'rows': 3}),
        }

main/views.py
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import UserForm, AbstractForm, PaperForm, AbstractReviewForm, PaperReviewForm, ParticipantProfileForm, AssignProfessorForm, AbstractReUploadForm, PaperAbstractNewForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from main.models import Abstract, Paper, ParticipantProfile, ProfessorProfile, StaffProfile, College, SupervisorProfile, Category
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings
# from pydrive.auth import GoogleAuth
# from pydrive.drive import GoogleDrive
import sys
import os
import datetime
from django.utils import timezone
import pytz
from django_file_md5 import calculate_md5
from threading import Thread
from main.driveupload import upload_thread
from django.template.loader import get_template
import random
from datetime import datetime



def start_new_thread(function):
    def decorator(*args, **kwargs):
        t = Thread(target=function, args=args, kwargs=kwargs)
        t.daemon = True
        t.start()
    return decorator


def paper_presentation(request):
    return HttpResponseRedirect(reverse('main:portal'))
    # return render(request, 'main/paper-presentation/paper-presentation.html', {})


def about(request):
    return render(request, 'main/paper-presentation/about.html', {})


def register(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('main:portal'))

    colleges = College.objects.all()

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        participant_profile_form = ParticipantProfileForm(data=request.POST)

        if user_form.is_valid() and participant_profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            participant_profile = participant_profile_form.save(commit=False)
            participant_profile.user = user
            participant_profile.save()

            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('main:portal'))
            else:
                return render(request, 'main/paper-presentation/login.html', {'login_form_errors': 'Your account is disabled'})
            return HttpResponseRedirect(reverse('main:user_login'))
        else:
            print(user_form.errors, participant_profile_form.errors)
    else:
        user_form = UserForm()
        participant_profile_form = ParticipantProfileForm()
    return render(request,
                  'main/paper-presentation/register.html',
                  {'user_form': user_form,
                   'participant_profile_form': participant_profile_form,
                   'colleges': colleges
                   })


def user_login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('main:portal'))
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                if user.username == 'pepadmin':
                    return HttpResponseRedirect(reverse('main:pepadmin'))
                else:
                    return HttpResponseRedirect(reverse('main:portal'))

            else:
                return render(request, 'main/paper-presentation/login.html', {'login_form_errors': 'Your account is disabled'})
        else:
            return render(request, 'main/paper-presentation/login.html', {'login_form_errors': 'Invalid Username/Password'})
    else:
        return render(request, 'main/paper-presentation/login.html', {})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:user_login'))


def user_trouble_logging_in(request):
    if request.method == 'POST':
        check_email = request.POST.get('email')
        users = User.objects.filter(email=check_email)
        if users is not None:
            for user in users:
                new_password = User.objects.make_random_password()
                subject = 'Paper Presentation APOGEE - Password Reset'
                message = 'Your new password for username ' + \
                    user.username + ' is: ' + new_password
                message += '\n\n\nRegards,\nAtharva Tandon\nCoordinator,\nDepartment of Paper Evaluation and Presentation\n\nAPOGEE 2019 | BITS Pilani | +91 8209411724'
                email_from = settings.EMAIL_HOST_USER
                recipient_list = [check_email, ]
                send_mail(subject, message, email_from, recipient_list)
                user.set_password(new_password)
                user.save()
            return render(request, 'main/paper-presentation/user-trouble-logging-in.html', {'status': "Check your email for new password"})
        else:
            return render(request, 'main/paper-presentation/user-trouble-logging-in.html', {'status': "No Account associated with " + check_email})
    else:
        return render(request, 'main/paper-presentation/user-trouble-logging-in.html', {})


@login_required
def user_password_change(request):
    if request.method == 'POST':
        check_email = request.POST.get('email')
        old_password = request.POST.get('old_password')
        new_password = request.POST.get('new_password')
        user = request.user
        if user.check_password(old_password) and user.email == check_email:
            user.set_password(new_password)
            user.save()
            subject = 'Paper Presentation APOGEE - Password Change'
            message = 'Your password for username ' + user.username + ' was changed'
            message += '\n\n\nRegards,\nAtharva Tandon\nCoordinator,\nDepartment of Paper Evaluation and Presentation\n\nAPOGEE 2019 | BITS Pilani | +91 8209411724'
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [check_email, ]
            send_mail(subject, message, email_from, recipient_list)
            logout(request)
            return HttpResponseRedirect(reverse('main:portal'))
        else:
            return render(request, 'main/paper-presentation/password-change.html', {'status': 'Incorrect Email/Old Password'})
    else:
        return render(request, 'main/paper-presentation/password-change.html', {})


@login_required
def portal(request):
    if request.user.is_superuser:
        # return HttpResponseRedirect('/admin')
        return HttpResponseRedirect('/paper-presentation/admin')

    if SupervisorProfile.objects.filter(user=request.user):
        user_profile = SupervisorProfile.objects.get(user=request.user)
        access_level = 3
        staff_allotted_list = []
        for supervisor_category in user_profile.categories.all():
            for staff in StaffProfile.objects.all():
                for staff_category in staff.categories.all():
                    if supervisor_category == staff_category:
                        if staff not in staff_allotted_list:
                            staff_allotted_list.append(staff)

        abstracts_allotted = []
        for abstract in Abstract.objects.filter(staff__in=staff_allotted_list):
            if abstract not in abstracts_allotted:
                abstracts_allotted.append(abstract)

        professors = ProfessorProfile.objects.all()
        assign_professor_form = AssignProfessorForm()
        return render(request, 'main/paper-presentation/portal.html', {'user_profile': user_profile,
                                                                       'access_level': access_level,
                                                                       'staff_allotted_list': staff_allotted_list,
                                                                       'abstracts_allotted': abstracts_allotted,
                                                                       'professors': professors,
                                                                       'assign_professor_form': assign_professor_form})

    elif StaffProfile.objects.filter(user=request.user):
        user_profile = StaffProfile.objects.get(user=request.user)
        access_level = 2
        abstracts_allotted = Abstract.objects.filter(staff=user_profile)
        professors = ProfessorProfile.objects.all()
        # professors = ProfessorProfile.objects.filter(category_id__in=[category.id for category in user_profile.categories.all()])
        assign_professor_form = AssignProfessorForm()
        return render(request, 'main/paper-presentation/portal.html', {'user_profile': user_profile,
                                                                       # 'categories': categories,
                                                                       'access_level': access_level,
                                                                       'abstracts_allotted': abstracts_allotted,
                                                                       'professors': professors,
                                                                       'assign_professor_form': assign_professor_form})

    elif ProfessorProfile.objects.filter(user=request.user):
        user_profile = ProfessorProfile.objects.get(user=request.user)
        access_level = 1
        abstracts_allotted = Abstract.objects.filter(professor=user_profile)
        papers_allotted = []
        papers = Paper.objects.all()
        for paper in papers:
            if paper.abstract in abstracts_allotted:
                papers_allotted.append(paper)
                abstracts_allotted = abstracts_allotted.exclude(
                    uid=paper.abstract.uid)

main/templates/main/paper-presentation/abstract-and-paper-upload.html
{% extends 'main/paper-presentation/base.html' %}
{% load staticfiles %}
{% block title %}
Upload Abstract
{% endblock %}

{% block body %}
<div class="abstract_upload">
	<div id="abstract-upload-card" class="row card-panel">
		<div class="row">
			<form class="col s12" id="paper_abstract_submission" method="post" enctype="multipart/form-data" action="{% url 'main:paper_abstract_submission' %}">
				{% csrf_token %}
				{{ abstract_form.as_p }}
				{{ paper_form.as_p }}
				<div class="row">
					<button class="btn waves-effect waves-light col blue" type="submit" name="action">Upload
						<i class="material-icons right">arrow_upward</i>
					</button>
				</div>
				<div class="red-text">
					{{ abstract_form_errors }}
					{{ paper_form_errors }}
				</div>
			</form>
		</div>
		<div class="row">
			Please upload both, Abstract and Paper in pdf format only.<br>
			<a href="https://drive.google.com/file/d/0B0bolFCiF4UtMnN2ZjAwclpEeFdJVUhzY0RnY19UMWJiR1Rn/view" target="_">Click
				here for Abstract
				Format</a><br>
			<a href="https://drive.google.com/file/d/1mNk0fJHjQOFBAL2TihYvP7MlG6grAG_H/view" target="_">Click here for Paper
				Format</a>
		</div>
	</div>
</div>
{% endblock %}

main/templates/main/paper-presentation/abstract-upload.html
{% extends 'main/paper-presentation/base.html' %} 
{% load staticfiles %}
{% block title %}
  Upload Abstract
{% endblock %}

{% block body %}
<div class="abstract_upload">
	<div id="abstract-upload-card" class="row card-panel">
		<div class="row">
		  	<form class="col s12" id="abstract_submission" method="post" enctype="multipart/form-data" action="{% url 'main:abstract_submission' %}">
				{% csrf_token %}
		    {{ abstract_form.as_p }}
		    <div class="row">
		      <button class="btn waves-effect waves-light col blue" type="submit" name="action">Upload
		        <i class="material-icons right">arrow_upward</i>
		      </button>
				</div>
				<div class="red-text">
					{{ abstract_upload_form_errors }}
				</div>
		  </form>
		</div>
	</div>
</div>
{% endblock %}

main/templates/main/paper-presentation/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <style>

    body {
    display: flex;
    min-height: 100vh;
    flex-direction: column;
    }

    main {
    flex: 1 0 auto;
    } 
    .paper-title-card {
      overflow: auto;
      display: flex;
      flex-direction: column;
      width: 30em;
      height: 20em;
      /*justify-content: space-between;*/
    }

	.paper-title-card-span { 
		display: inline !important;
	}

  #modal-rules-regulations{
    line-height: 26px;
  }

  .errorlist {
    color:red;
    margin-left: 50px;
  }

	.paper-title-card-div { 
		display: flex;
		justify-content: space-between;
	}

    .paper-title-bottom {
      margin-top: 30px;
      display: flex;
      position: absolute;
      bottom:1em;
      align-items: center;
      justify-content: space-between;
    }

	.author-info-card {
		flex-grow: 1;	
		align-items: flex-end;
		display: flex;
	}

    .paper-title-bottom-btns {
      display: flex;
      align-items: center;
      padding-left: 20px;
      justify-content: space-around;
    }

    .brand-logo {
      padding-left: 12px !important;
      position: static !important;
    }

    .login-form {
      padding: 10px !important;
    }

    .tabs{
      margin-top: 5px;
    }

    .paper-upload {
      padding: 10px !important;
    }

    .feedback-btn {
      font-size: 10px !important;
    }

    #login_form, .login-form, #user_form, .abstract_upload{
      display: flex;
      justify-content: center;
      flex-direction: column;
      align-items: center;
    }

    .footer-copyright .container {
        display: flex;
        justify-content: center;
    }

    .nav-wrapper, .page-footer, .footer-copyright, .nav-wrapper .right .dropdown-content, .btn, #modal-rules-regulations{
        background: linear-gradient(45deg, #38b0ec 0%, #9870FC 100%) !important;
    }

    .nav-wrapper {
      display: flex;
      /*flex-wrap: wrap;*/
      justify-content: space-between;
      align-items: center;
    }

    .right {
      z-index: 999;
    }

    #pep-logo {
      max-height: 40px;
    }

    #dashboard-title {
      display: flex;
      align-items: center;
      padding-left: 10px;
    }

    .tabs .tab a{
        color:#000;
    } /*Black color to the text*/

    .tabs .tab a:hover {
        background-color:#eee;
        color:#000;
    } /*Text color on hover*/

    .tabs .tab a.active {
        background-color:rgba(0,0,255,0.05);
        color:#000;
    } /*Background and text color when a tab is active*/

    .tabs .indicator {
        background-color:rgba(0,0,255,0.5);
    } /*Color of underline*/

    #contact-content-right {
      text-align: right;
    }

    #footer-row {
      display: flex;
    }
    #user-papers {
      display: flex;
      flex-wrap: wrap;
    }
    .abstract-card {
      width: auto !important;
      margin-left: 0 !important;
    }
    
    @media all and (min-width: 700px) {
        #register-card {
            width:700px;
        }

        #abstract-upload-card {
            width:700px;
            margin-top: 10vh;
        }

        #login_card {
            margin-top: 7vh;
        }
    }
    @media all and (max-width: 600px) {
      .brand-logo {
        font-size: 30px !important;
      }

      #footer-row {
        flex-wrap: wrap;
        justify-content: center;
      }

      .contact-content {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        text-align: center;
      }

      .paper-title-bottom {
        flex-wrap: wrap;
        justify-content: center;
      }
      #contact-content-right{
        text-align: center;
      }
    }
    @media all and (max-width: 260px) {
      #dashboard-title {
        display: none;
      }
      .nav-wrapper {
        justify-content: center;
      }
    }
    @media all and(max-width: 420px) {
      .paper-title-bottom-btns {
        padding: 0;
      }
    }
    @media all and (max-width: 1000px) {
      #user-papers {
        justify-content: center;
      }
    }
  </style>

  <!-- Compiled and minified JavaScript -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <title>Portal {% block title %}{% endblock %}</title>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
  <header>
    <nav>
      <div class="nav-wrapper">
        <a href="{% url 'main:portal' %}" class="" id="dashboard-title">
          <img src=" {% static 'main/paper-presentation/images/logo.png' %}" id="pep-logo">
        </a>
        <ul class="right">
          {% if access_level == 0%}
          <li><a class="dropdown-trigger" href="#" data-target="dropdown2"><i class="material-icons center white-text">add</i></a></li>
          {% endif %}
          <!-- Dropdown Trigger -->
          {% if request.user.is_authenticated %}
          <li><a class="dropdown-trigger" href="#" data-target="dropdown1">{{ request.user.username }}<i class="material-icons right">arrow_drop_down</i></a></li>
          {% else %}
          <li><a data-target="modal-rules-regulations" class="modal-trigger">Rules &amp Regulations</a></li>
          {% endif %}

        </ul>
        <ul id="dropdown1" class="dropdown-content">
          <li><a data-target="modal-rules-regulations" class="modal-trigger white-text">Rules</a></li>
          <li class="divider" tabindex="-1"></li>
          <li><a href="{% url 'main:user_password_change' %}" class="white-text">Change Password</a></li>
          <li><a href="{% url 'main:user_logout' %}" class="white-text">Logout</a></li>
        </ul>
        <ul id="dropdown2" class="dropdown-content">
          <!--<li><a href="{% url 'main:abstract_submission' %}" class="white-text">Add Abstract</a></li>-->
          <li><a href="{% url 'main:paper_submission' %}" class="white-text">Add Paper</a></li>
        </ul>
        <!-- Modal Structure -->
        <div id="modal-rules-regulations" class="modal">
          <div class="modal-content">
            <h4 align="center">Rules &amp Regulations</h4><br><br>
            <li>A particular paper can be presented only in one category. Also, participants can present more than one
              paper. However, the abstracts should be submitted separately.</li>
            <li>Only genuine and original paper abstracts should be uploaded. Abstracts found copied from any source
              like internet/ journals etc. will be disqualified. Plagiarized content will be strictly dealt with and
              would lead to participant's disqualification. In case of any discrepancy, organizers decision will be
              final and binding.</li><br><br>
            <u><a href="https://drive.google.com/file/d/0B0bolFCiF4UtMnN2ZjAwclpEeFdJVUhzY0RnY19UMWJiR1Rn/view?usp=sharing"
                target="_">Click here for Abstract Format</a><br></u>
            <u><a href="https://drive.google.com/a/bits-apogee.org/file/d/1mNk0fJHjQOFBAL2TihYvP7MlG6grAG_H/view?usp=drivesdk"
                target="_">Click here for Paper Format</a></u><br>
            <div class="red-text">
              Note: Only PDF file Format is Supported<br>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main>
    {% block body%}
    {% endblock %}
  </main>
  <footer class="page-footer blue accent-3">
    <div class="container">
      <div class="row" id="footer-row">
        <div class="col l6 s12 contact-content">
          <h4><a class="white-text" href="#">APOGEE 2019</a></h4>
          <ul>
            <li><a class="grey-text text-lighten-3">The Reality Roulette</a></li>
          </ul>
        </div>
        <div id="contact-content-right" class="col l4 offset-l2 s12 contact-content">
          <h4><a class="white-text" href="#">Contact Us</a></h4>
          <ul>
            <li><a class="grey-text text-lighten-3">Atharv Tandon</a></li>
            <li><a class="grey-text text-lighten-3">Coordinator</a></li>
            <li><a class="grey-text text-lighten-3">Department of Paper Evaluation and Presentation</a></li>
            <li><a class="grey-text text-lighten-3" href="tel:+91-8209411724">+91-8209411724</a></li>
            <li><a class="grey-text text-lighten-3" href="mailto:pep@bits-apogee.org">pep@bits-apogee.org</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        <a class="grey-text text-lighten-4">Made with &hearts; by PEP</a>
      </div>
    </div>
  </footer>
  <script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function () {
      var elems = document.querySelectorAll('.modal');
      var instances = M.Modal.init(elems, {});
      $(".dropdown-trigger").dropdown();
      $('.tabs').tabs();
    });

    document.addEventListener('DOMContentLoaded', function () {
      var elems = document.querySelectorAll('.dropdown-trigger');
      var instances = M.Dropdown.init(elems, options);
    });


    document.addEventListener('DOMContentLoaded', function () {
      var elems = document.querySelectorAll('select');
      var instances = M.FormSelect.init(elems, {});
    });

    function validateEmail(email) {
      var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
      return re.test(String(email).toLowerCase());
    }

    document.getElementById("user_form").onsubmit = function (e) {
      var email = document.getElementById("id_email").value,
        phone = document.getElementById("id_phone1").value;
      //altphone = document.getElementById("id_phone2").value;

      if (!validateEmail(email)) {
        document.getElementById("front_email_err").innerHTML = "Enter a valid email address";
        e.preventDefault();
      }
      else {
        document.getElementById("front_email_err").innerHTML = "";
      }

      if (phone.length != 10) {
        document.getElementById("front_phone_err").innerHTML = "Enter a valid phone number";
        e.preventDefault();
      }
      else {
        document.getElementById("front_phone_err").innerHTML = "";
      }

      // if (altphone.length != 10) {
      //     document.getElementById("front_altphone_err").innerHTML = "Enter a valid phone number";
      //     e.preventDefault();
      // }
      // else {
      //     document.getElementById("front_altphone_err").innerHTML = "";
      // }
    }
  </script>
</body>

</html>

main/templates/main/paper-presentation/login.html
{% extends 'main/paper-presentation/base.html' %}
{% load staticfiles %}
{% block title %}
Login
{% endblock %}
{% block body %}
<div class="login-form col" style="height: 100%; display: flex; justify-content: center">
    <div id="login_card" class="row card-panel hoverable">
        <form class="col s12" id="login_form" , method="post" action="{% url 'main:user_login' %}">
            {% csrf_token %}
            <h5>Sign In</h5>
            <br>
            {% if login_form_errors %}
            <div class="red-text">
                {{ login_form_errors }}
            </div>
            {% endif %}
            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix">account_circle</i>
                    <input type="text" name="username" id="username" required>
                    <label for="username">Username</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <i class="material-icons prefix">lock</i>
                    <input id="password" type="password" name="password" required>
                    <label for="password">Password</label>
                </div>
            </div>
            <div class="row">
                <button class="btn waves-effect waves-light col blue" type="submit" name="action">Login
                    <i class="material-icons right">arrow_forward</i>
                </button>
            </div>
            <div class="row">
                <a class="waves-effect waves-light btn blue" href="{% url 'main:register' %}">Create Account<i class="material-icons right">add</i>
                </a>
            </div>
            <div class="row"></div>
            <a class="waves-effect waves-light btn blue" href="{% url 'main:user_trouble_logging_in' %}">Trouble
                Logging
                in?
            </a>
    </div>
    </form>
</div>
</div>
{% endblock %}

main/templates/main/paper-presentation/paper-review.html
<!DOCTYPE html>
<html>
<head>
  <title>Abstract</title>
</head>
<body>
	Paper Title: {{ abstract.title }}<br>
	Paper UID: {{ abstract.uid }}<br>
	Status: {{ paper.status }}<br><br>
  <form method="post">
    {% csrf_token %}
    {{ paper_review_form.as_p }}
    <button type="submit">
      Submit
    </button>
  </form>
</body>
</html>

main/templates/main/paper-presentation/pepadmin.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>PEP Admin</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="stylesheet" type="text/css" media="screen" href="main.css" /> -->
    <!-- <script src="main.js"></script> -->
</head>
<body>
    {{ response }}
    <button>
        <a href="{% url 'main:upload_to_drive' 0 %}">
            Upload to Drive
        </a>
    </button>
    <button>
        <a href="{% url 'main:upload_to_drive' 1 %}">
            Flush record and Upload to Drive
        </a>
    </button>
    <button> 
        <a href="{% url 'main:check_duplicate_abstracts' %}">
            Check Duplicates
        </a>
    </button>
</body>
</html>